name: task4
on: 
  workflow_dispatch:
  push:
    branches: [ jiashi ]
jobs:
  Assemble:
    runs-on: self-hosted
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Construyendo el c贸digo
        run: |       
          chmod +x gradlew        
          ./gradlew assemble
      - run: echo "jiashi"
  Test:
    needs: Assemble
    runs-on: self-hosted
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Probando el c贸digo
        run: |
          chmod +x gradlew 
          ./gradlew test
      - run: echo "jiashi"
name: task4
on: 
  push:
    branches: [ arreglosJunio ]
jobs:
  Build:
    runs-on: self-hosted
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clonando el repositorio y estableciendo el espacio de trabajo
        uses: actions/checkout@v3
      - name: Configurando java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: Construyendo el c贸digo
        run: |       
          chmod +x gradlew        
          ./gradlew build
      - run: echo "jiashi"
  Publish:
    needs: Build
    runs-on: self-hosted
    env:
      GITHUB_LOGIN: ${{ github.actor }}
      GITHUB_PACKAGES: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Probando el c贸digo
        run: |
          chmod +x gradlew 
          ./gradlew publish
      - run: echo "jiashi"
